name: audiobooks_app
description: Audio books app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  cupertino_icons: ^1.0.2
  audioplayer: ^0.8.1
  rxdart: ^0.25.0
  audio_service:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: one-isolate
  flutter_playout: ^1.0.42

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/minecraft/cifrova_zagroza/
    - assets/minecraft/deep_dive/
    - assets/minecraft/night_of_the_bats/
    - assets/minecraft/dungeon_secrets/
    - google_fonts/